CREATE TABLE IF NOT EXISTS jobs (
  id SERIAL PRIMARY KEY,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  payload TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs (status);

DROP USER IF EXISTS faultlab_app;
CREATE USER faultlab_app WITH PASSWORD 'faultlab_app' LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT CONNECT ON DATABASE pipeline TO faultlab_app;
GRANT USAGE ON SCHEMA public TO faultlab_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO faultlab_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO faultlab_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO faultlab_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO faultlab_app;
